apiVersion: v1
kind: Secret
metadata:
  name: pricepulse-secrets
  labels:
    {{- include "pricepulse.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL:       {{ .Values.secrets.databaseUrl | quote }}
  SENDGRID_API_KEY:   {{ .Values.secrets.sendgridApiKey | quote }}
  SLACK_WEBHOOK_URL:  {{ .Values.secrets.slackWebhookUrl | quote }}
  GCS_SNAPSHOT_BUCKET: {{ .Values.secrets.gcsSnapshotBucket | quote }}
